version: '3.1'

services:

  redis:
    image: redis
    container_name: cache-latam
    expose:
      - 6379
  
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server --address 0.0.0.0:9000 /data

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: project

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
        - mongo
    ports:
      - 8888:8081


  app:
    image: python:3
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    links:
      - redis:redis
      - minio:minio
      - mongo:mongo
  
  worker:
    image: python:3
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    links:
      - redis:redis
      - minio:minio
      - mongo:mongo 
